title: Services
tabs:
	content:
		label: Contenu
		icon: text
		columns:
			left:
				fields:
					services:
						label: Services
						type: structure
						duplicate: false
						fields:
							name:
								label: Nom
								type: text
								required: true
								width: 1/3
							secondary:
								type: toggle
								label: Service secondaire
								text:
									Non
									Oui
								width: 1/3
							icon:
								type: files
								uploads:
									template: social
								label: Icone
								min: 1
								max: 1
								sortBy: filename
								layout: cards
								size: medium
								width: 1/3
							description:
								label: Description
								type: textarea
								required: true
	seo:
		label: Référencement
		icon: search
		columns:
			seo:
				width: 2/3
				fields:
					meta: fields/seo